ansible_connection: ssh
ansible_user: kali
ansible_password: kali
ansible_become_password: kali
ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PreferredAuthentications=password -o PubkeyAuthentication=no'
